name: Build
on:
    - push
    - pull_request

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21
            - name: Set up gradle cache
              uses: gradle/actions/setup-gradle@v3
            - name: Build with gradle
              run: ./gradlew clean test remapJar --stacktrace
